# Use the latest .NET SDK image
FROM mcr.microsoft.com/dotnet/sdk:8.0.400 AS build
WORKDIR /app

# Copy csproj and restore as distinct layers to improve caching
COPY *.csproj ./
RUN dotnet restore --packages /root/.nuget/packages

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out --no-restore --packages /root/.nuget/packages

# Use runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "ConnorAPI.dll"]
