# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy the project file and restore dependencies as a separate layer
COPY ["ConnorAPI.csproj", "./"]
RUN dotnet restore --packages /root/.nuget/packages

# Copy the rest of the application code and build the app
COPY . .
RUN dotnet publish -c Release -o /app --no-restore --packages /root/.nuget/packages

# Stage 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "ConnorAPI.dll"]
